         ----------------------CREATE DATABASE-----------------
				  
CREATE DATABASE ecommerce_analysis;

         ---------------------CREATE TABLE--------------------

CREATE TABLE data_order (
orderid VARCHAR(20),
date DATE,
customerid VARCHAR(20),
product VARCHAR(100),
quantity INT,
unitprice NUMERIC(10,2),
shippingaddress TEXT,
paymentmethod VARCHAR(50),
orderstatus VARCHAR(50),
trackingnumber VARCHAR(30),
itemsincart INT,
couponcode VARCHAR(30),
referralsource VARCHAR(50),
totalprice NUMERIC(10,2)
);


          ------------------- DATA CLEANING-------------------

					
SELECT COUNT(*) AS total_records
FROM data_order;

SELECT * 
FROM data_order
LIMIT 5;

SELECT *                                --CHECKING NULL VALUES
FROM data_order
WHERE 
orderid IS NULL
OR customerid IS NULL 
OR quantity IS NULL 
OR quantity IS NULL 
OR unitprice IS NULL
OR TOTALPRICE IS NULL;

SELECT orderid,                           --DUPLICATE RECORD FIND
COUNT(*)
FROM data_order
GROUP BY orderid
HAVING COUNT(*)>1;

SELECT COUNT(DISTINCT orderid)               --UNIQUE ORDER CHECK
FROM data_order;

SELECT                                         --CHECK DATE RANGE
MIN(date),
MAX(date)
FROM data_order;

SELECT                                       --CHECK ORDER STATUS
orderstatus,
COUNT(*)
FROM data_order
GROUP BY orderstatus;

SELECT                                      --CHECK PAYMENT METHOD
paymentmethod, 
COUNT(*)
FROM data_order
GROUP BY paymentmethod;

SELECT                                    --CHECK PRODUCT CATEGORY
product,
COUNT(*)
FROM data_order
GROUP BY product
ORDER BY COUNT(*) DESC;

SELECT *                             --VERY TOTAL PRICE CALCULATION
FROM data_order
WHERE totalprice <> quantity * unitprice;

SELECT                                      --CHECK ITEMS IN CART 
MIN(itemsincart),
MAX(itemsincart),
AVG(itemsincart)
FROM data_order;

SELECT                                    -- CHECKING COUPON USAGE 
couponcode,
COUNT(*)
FROM data_order
GROUP BY couponcode;



            ----------------------------QUERIES------------------------------



--QUERY-1 -What is the overall health of the business?
SELECT
    COUNT(orderid) AS Total_Orders,
    COUNT(DISTINCT customerid) AS Unique_Customers,
    ROUND(SUM(totalprice),2) AS Total_Revenue,
    ROUND(AVG(totalprice),2) AS Average_Order_Value,
    ROUND(AVG(itemsincart),2) AS Average_Basket_Size
FROM data_order;
    ---Increase Average Basket Size through combo offers and product bundling.


--QUERY-2 -What percentage of total revenue is generated by each product?
SELECT
    product,
    ROUND(
        SUM(totalprice) * 100.0 /
        (SELECT SUM(totalprice) FROM data_order),
        2
    ) AS Revenue_Percentage
FROM data_order
GROUP BY product
ORDER BY Revenue_Percentage DESC;


--QUERY-3 -Revenue Lost due to Cancelled Orders?
SELECT 
    COUNT(*) AS Cancelled_Orders,
    ROUND(SUM(totalprice),2) AS Revenue_Lost
FROM data_order
    WHERE orderstatus = 'Cancelled';


--QUERY-4 -Revenue Lost due to Returned Orders?
SELECT
    COUNT(*) AS Returned_Orders,
    ROUND(SUM(totalprice),2) AS Returned_Revenue
FROM data_order
WHERE orderstatus='Returned';


-- QUERY-5 -what is the total Revenue Loss % ?
SELECT
ROUND(SUM(CASE 
WHEN orderstatus IN ('Cancelled','Returned')
THEN totalprice
ELSE 0
END)*100/SUM(totalprice),2) AS Revenue_Loss_Percentage
FROM data_order;

--QUERY-6 -Which product drives maximum business OR generate highest revenue?
SELECT 
product,
ROUND(SUM(totalprice)*100/(SELECT SUM(totalprice)FROM data_order),2) Contribution_Percentage
FROM data_order
GROUP BY product
ORDER BY Contribution_Percentage DESC;


--QUERY-7 -Which products are cancelled most frequently, and should the business investigate them?
SELECT
    product,
    COUNT(*) AS Cancelled_Orders
FROM data_order
WHERE orderstatus = 'Cancelled'
GROUP BY product
ORDER BY Cancelled_Orders DESC;


--QUERY-8 -High Revenue + Low Quantity = Premium Products
SELECT
product,
SUM(quantity) AS  Qty,
SUM(totalprice) AS Revenue,
ROUND(SUM(totalprice)/SUM(quantity),2) Revenue_Per_Unit
FROM data_order
GROUP BY product
ORDER BY Revenue_Per_Unit DESC;


--QUERY-9 -Which channel deserves more budget?
SELECT
referralsource,
COUNT(*) Orders,
SUM(totalprice) Revenue,
ROUND(AVG(totalprice),2) AS Avg_Order,
ROUND(SUM(totalprice)/COUNT(*),2) AS Revenue_Per_Order
FROM data_order
GROUP BY referralsource
ORDER BY Revenue DESC;


--QUERY-10 -How can customers be ranked based on their total spending?
SELECT
    customerid,
    SUM(totalprice) AS Revenue,
    RANK() OVER(ORDER BY SUM(totalprice) DESC) AS Customer_Rank
FROM data_order
GROUP BY customerid;


--QUERY-11 -Did discounts(COUPONS) actually improve revenue?
SELECT
CASE
WHEN couponcode IS NULL
THEN 'Without Coupon'
ELSE 'With Coupon'
END Coupon_Status,
COUNT(*) Orders,
SUM(totalprice)  AS Revenue,
AVG(totalprice) AS Avg_Order
FROM data_order
GROUP BY Coupon_Status;


--MOST SUCESSFUL COUPON 
SELECT
couponcode,
COUNT(*) Orders,
SUM(totalprice) Revenue
FROM data_order
GROUP BY couponcode
ORDER BY Revenue DESC;


--QUERY-12 -Which payment method is the most profitable for the business based on total revenue,
--average order value, and highest transaction value?
SELECT
paymentmethod,
COUNT(*) Orders,
SUM(totalprice) AS Revenue,
ROUND(AVG(totalprice),2) AS  Average_Order,
MAX(totalprice) AS Highest_Order
FROM data_order
GROUP BY paymentmethod
ORDER BY Revenue DESC;

--QUERY-13 -Monthly Business Growth
SELECT
EXTRACT(YEAR FROM date)  AS Year,
EXTRACT(MONTH FROM date) AS Month,
SUM(totalprice) Revenue
FROM data_order
GROUP BY Year,Month
ORDER BY Year,Month;

--Best Sales Month
SELECT
EXTRACT(MONTH FROM date) AS Month,
SUM(totalprice) AS Revenue
FROM data_order
GROUP BY Month
ORDER BY Revenue DESC
LIMIT 1;


--QUERY-14 -What is the distribution of orders across different order statuses, 
          ----and what percentage of total orders does each status represent?
SELECT
orderstatus,
COUNT(*) Orders,
ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM data_order),2) Percentage
FROM data_order
GROUP BY orderstatus;


--QUERY-15 -Do the top 20% customers contribute the majority of business revenue?
WITH customer_sales AS(
SELECT
customerid,
SUM(totalprice) AS revenue,
RANK() OVER(ORDER BY SUM(totalprice) DESC) AS customer_rank
FROM data_order
GROUP BY customerid)
SELECT *
FROM customer_sales
ORDER BY customer_rank
LIMIT 20;


--QUERY-15 — Which Payment Method Has the Highest Cancellation Rate?
SELECT
paymentmethod,
COUNT(*) AS Cancelled_Orders
FROM data_order
WHERE orderstatus='Cancelled'
GROUP BY paymentmethod
ORDER BY Cancelled_Orders DESC;


--QUERY-16 -Which customers purchase most frequently?
SELECT
customerid,
COUNT(orderid) AS Orders
FROM data_order
GROUP BY customerid
ORDER BY Orders DESC;

--QUERY-17 -what is the Month-over-Month Growth?
WITH MonthlySales AS(
SELECT
DATE_TRUNC('month', date) AS month,
SUM(totalprice) AS revenue
FROM data_order
GROUP BY DATE_TRUNC('month', date)
)
SELECT
month,
revenue,
LAG(revenue) OVER(ORDER BY month) AS Previous_Revenue,
ROUND(((revenue - LAG(revenue) OVER(ORDER BY month))
/
LAG(revenue) OVER(ORDER BY month)
)*100,2
) AS Growth_Percentage
FROM MonthlySales;


--QUERY-17 - How can customers be segmented based on their total spending to identify VIP, Gold, Silver, 
--and Regular customers for targeted marketing and customer retention strategies?
SELECT
customerid,
SUM(totalprice) Revenue,
CASE
WHEN SUM(totalprice)>=5000 THEN 'VIP'
WHEN SUM(totalprice)>=3000 THEN 'Gold'
WHEN SUM(totalprice)>=1000 THEN 'Silver'
ELSE 'Regular'
END Customer_Type
FROM data_order
GROUP BY customerid
ORDER BY Revenue DESC;